<?php

declare(strict_types=1);
namespace App\Services;
use DateTimeImmutable;
use DateTimeZone;
use PDO;

final class PeriodReviewService
{
    public const PERIODS=['day','week','month','year'];public const REVIEW_TYPES=['pre','post'];public const GOAL_TYPES=['process','risk','psychology','performance','custom'];
    public static function settings(PDO $db,int $uid):array{$q=$db->prepare('SELECT * FROM review_settings WHERE user_id=?');$q->execute([$uid]);$s=$q->fetch();if($s)return$s;$db->prepare('INSERT INTO review_settings(user_id,timezone) VALUES(?,?) ON DUPLICATE KEY UPDATE user_id=user_id')->execute([$uid,'America/Sao_Paulo']);$q=$db->prepare('SELECT * FROM review_settings WHERE user_id=?');$q->execute([$uid]);return$q->fetch()?:['user_id'=>$uid,'timezone'=>'America/Sao_Paulo','day_pre_time'=>'08:00:00','day_post_time'=>'18:00:00','week_pre_day'=>1,'week_pre_time'=>'08:00:00','week_post_day'=>5,'week_post_time'=>'18:00:00','month_pre_day'=>1,'month_pre_time'=>'08:00:00','month_post_time'=>'18:00:00','year_pre_month'=>1,'year_pre_day'=>1,'year_pre_time'=>'08:00:00','year_post_month'=>12,'year_post_day'=>31,'year_post_time'=>'18:00:00'];}
    public static function ensureCurrent(PDO $db,int $uid,?DateTimeImmutable $now=null):array{$s=self::settings($db,$uid);$tz=new DateTimeZone((string)$s['timezone']);$now=($now?:new DateTimeImmutable('now',$tz))->setTimezone($tz);$reviews=[];foreach(self::PERIODS as $period){foreach(self::REVIEW_TYPES as $type){[$start,$end,$scheduled]=self::period($period,$type,$now,$s);$q=$db->prepare('INSERT INTO period_reviews(user_id,period_type,review_type,period_start,period_end,scheduled_at,status) VALUES(?,?,?,?,?,? ,"pending") ON DUPLICATE KEY UPDATE scheduled_at=VALUES(scheduled_at)');$q->execute([$uid,$period,$type,$start->format('Y-m-d'),$end->format('Y-m-d'),$scheduled->format('Y-m-d H:i:s')]);$id=(int)$db->lastInsertId();if(!$id){$q=$db->prepare('SELECT id FROM period_reviews WHERE user_id=? AND period_type=? AND review_type=? AND period_start=?');$q->execute([$uid,$period,$type,$start->format('Y-m-d')]);$id=(int)$q->fetchColumn();}$reviews[$period.'_'.$type]=['id'=>$id,'period_type'=>$period,'review_type'=>$type,'period_start'=>$start->format('Y-m-d'),'period_end'=>$end->format('Y-m-d'),'scheduled_at'=>$scheduled->format('Y-m-d H:i:s')];}}return$reviews;}
    private static function period(string $period,string $type,DateTimeImmutable $now,array $s):array{$day=$now->setTime(0,0,0);if($period==='day'){$start=$day;$end=$day;$time=$type==='pre'?$s['day_pre_time']:$s['day_post_time'];return[$start,$end,self::at($start,(string)$time)];}if($period==='week'){$start=$day->modify('monday this week');$end=$start->modify('+6 days');$weekday=(int)($type==='pre'?$s['week_pre_day']:$s['week_post_day']);$time=$type==='pre'?$s['week_pre_time']:$s['week_post_time'];return[$start,$end,self::at($start->modify('+'.max(0,$weekday-1).' days'),(string)$time)];}if($period==='month'){$start=$day->modify('first day of this month');$end=$start->modify('last day of this month');$time=(string)($type==='pre'?$s['month_pre_time']:$s['month_post_time']);return[$start,$end,self::at($type==='pre'?$start:$end,$time)];}$start=$day->setDate((int)$day->format('Y'),1,1);$end=$start->modify('last day of December');$time=(string)($type==='pre'?$s['year_pre_time']:$s['year_post_time']);$month=(int)($type==='pre'?$s['year_pre_month']:$s['year_post_month']);$d=(int)($type==='pre'?$s['year_pre_day']:$s['year_post_day']);$base=$start->setDate((int)$start->format('Y'),$month,1);$scheduled=$base->setDate((int)$base->format('Y'),$month,min($d,(int)$base->modify('last day of this month')->format('d')));return[$start,$end,self::at($scheduled,$time)];}
    private static function at(DateTimeImmutable $date,string $time):DateTimeImmutable{$p=explode(':',$time);return$date->setTime((int)($p[0]??0),(int)($p[1]??0),(int)($p[2]??0));}
    public static function current(PDO $db,int $uid):array{self::ensureCurrent($db,$uid);$q=$db->prepare('SELECT * FROM period_reviews WHERE user_id=? AND period_start<=CURDATE() AND period_end>=CURDATE() ORDER BY FIELD(period_type,"day","week","month","year"),FIELD(review_type,"pre","post")');$q->execute([$uid]);return$q->fetchAll();}
    public static function due(PDO $db,int $uid):array{self::ensureCurrent($db,$uid);$q=$db->prepare('SELECT * FROM period_reviews WHERE user_id=? AND status<>"completed" AND scheduled_at<=NOW() ORDER BY scheduled_at');$q->execute([$uid]);return$q->fetchAll();}
    public static function actionable(PDO $db,int $uid):array{return self::due($db,$uid);}
    public static function review(PDO $db,int $uid,int $id):?array{$q=$db->prepare('SELECT * FROM period_reviews WHERE id=? AND user_id=?');$q->execute([$id,$uid]);return$q->fetch()?:null;}
    public static function goals(PDO $db,int $uid):array{$q=$db->prepare('SELECT * FROM review_goals WHERE user_id=? AND is_active=1 ORDER BY name');$q->execute([$uid]);return$q->fetchAll();}
    public static function goalRows(PDO $db,int $uid,int $reviewId):array{$q=$db->prepare('SELECT rg.*,g.name,g.goal_type FROM period_review_goals rg JOIN review_goals g ON g.id=rg.goal_id JOIN period_reviews r ON r.id=rg.review_id AND r.user_id=? WHERE rg.review_id=? ORDER BY g.name');$q->execute([$uid,$reviewId]);return$q->fetchAll();}
    public static function achievement(PDO $db,int $uid,int $reviewId):?float{$q=$db->prepare('SELECT COUNT(*) total,SUM(status="hit") hits FROM period_review_goals pg JOIN period_reviews r ON r.id=pg.review_id WHERE pg.review_id=? AND r.user_id=?');$q->execute([$reviewId,$uid]);$r=$q->fetch();if(!$r||!(int)$r['total'])return null;return round(((int)$r['hits']/(int)$r['total'])*100,1);}
    public static function saveReview(PDO $db,int $uid,int $id,array $responses,array $goalIds,array $goalStatuses,array $goalNotes,array $targets=[]):void{$review=self::review($db,$uid,$id);if(!$review)throw new \InvalidArgumentException('Review not found.');$db->beginTransaction();try{$db->prepare('UPDATE period_reviews SET responses_json=?,status="completed",started_at=COALESCE(started_at,NOW()),completed_at=NOW() WHERE id=? AND user_id=?')->execute([json_encode($responses,JSON_THROW_ON_ERROR),$id,$uid]);$db->prepare('DELETE FROM period_review_goals WHERE review_id=?')->execute([$id]);$ins=$db->prepare('INSERT INTO period_review_goals(review_id,goal_id,target_value,target_unit,status,achieved_value,notes) SELECT ?,id,?,?,?,NULL,? FROM review_goals WHERE id=? AND user_id=?');foreach($goalIds as $gid){$gid=(int)$gid;if($gid<1)continue;$st=(string)($goalStatuses[$gid]??'pending');if(!in_array($st,['pending','hit','missed','not_applicable'],true))$st='pending';$target=(string)($targets[$gid]['value']??'');$unit=(string)($targets[$gid]['unit']??'');$note=trim((string)($goalNotes[$gid]??''));$ins->execute([$id,$gid,$target!==''?$target:null,$unit!==''?$unit:null,$st,$note,$gid,$uid]);}if($review['review_type']==='pre')self::copyPreGoalsToPost($db,$uid,$review);$db->commit();}catch(\Throwable $e){if($db->inTransaction())$db->rollBack();throw$e;}}
    private static function copyPreGoalsToPost(PDO $db,int $uid,array $pre):void{$q=$db->prepare('SELECT id FROM period_reviews WHERE user_id=? AND period_type=? AND review_type="post" AND period_start=?');$q->execute([$uid,$pre['period_type'],$pre['period_start']]);$postId=(int)$q->fetchColumn();if(!$postId)return;$db->prepare('DELETE FROM period_review_goals WHERE review_id=?')->execute([$postId]);$db->prepare('INSERT INTO period_review_goals(review_id,goal_id,target_value,target_unit,status,achieved_value,notes) SELECT ?,goal_id,target_value,target_unit,"pending",NULL,NULL FROM period_review_goals WHERE review_id=?')->execute([$postId,$pre['id']]);}
    public static function createGoal(PDO $db,int $uid,string $name,string $type='custom'):int{$name=trim($name);if($name===''||strlen($name)>160)throw new \InvalidArgumentException('Goal name is required.');if(!in_array($type,self::GOAL_TYPES,true))$type='custom';$q=$db->prepare('INSERT INTO review_goals(user_id,name,goal_type) VALUES(?,?,?) ON DUPLICATE KEY UPDATE is_active=1,goal_type=VALUES(goal_type)');$q->execute([$uid,$name,$type]);if($q->rowCount()===1)return(int)$db->lastInsertId();$q=$db->prepare('SELECT id FROM review_goals WHERE user_id=? AND name=?');$q->execute([$uid,$name]);return(int)$q->fetchColumn();}
    public static function blockTradeEntry(PDO $db,int $uid):void{$r=self::due($db,$uid);foreach($r as $x)if($x['period_type']==='day'&&$x['review_type']==='pre'&&$x['status']!=='completed')throw new \InvalidArgumentException('Day Pre Review is required before you can enter or import trade data.');}
    public static function dashboardGoalTrend(PDO $db,int $uid,string $period='day',int $limit=30):array{$limit=max(1,min(366,$limit));$q=$db->prepare('SELECT period_start,id FROM period_reviews WHERE user_id=? AND period_type=? AND review_type="post" AND status="completed" ORDER BY period_start DESC LIMIT '.$limit);$q->execute([$uid,$period]);$rows=array_reverse($q->fetchAll());$out=[];foreach($rows as $r){$a=self::achievement($db,$uid,(int)$r['id']);if($a!==null)$out[]=['period'=>$r['period_start'],'achievement'=>$a];}return$out;}
}
