<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/app/services/TradingConfigurationService.php';
require_once dirname(__DIR__) . '/app/services/TradeRiskService.php';

function phase3_trade_lookup(PDO $db, int $userId, string $table, int $id): ?array
{
    $allowed=['trading_systems'=>'id,name,ideal_risk,risk_tolerance','strategies'=>'id,name,trading_system_id','assets'=>'id,symbol,name,configuration','trading_sessions'=>'id,name,start_time,end_time,timezone'];
    if(!isset($allowed[$table])||$id<1)return null;
    $s=$db->prepare("SELECT {$allowed[$table]} FROM {$table} WHERE id=? AND user_id=?");$s->execute([$id,$userId]);return $s->fetch()?:null;
}

function phase3_trade_form_data(array $input,array $user):array
{
    $data=trade_form_data($input,$user);$db=db();$userId=(int)$user['id'];[$accountId]=$data;
    $q=$db->prepare('SELECT id,default_system_id FROM accounts WHERE id=? AND user_id=?');$q->execute([$accountId,$userId]);$account=$q->fetch();
    if(!$account)throw new InvalidArgumentException('The selected account is invalid.');
    $systemId=filter_var($input['trading_system_id']??null,FILTER_VALIDATE_INT);$strategyId=filter_var($input['strategy_id']??null,FILTER_VALIDATE_INT);$assetId=filter_var($input['asset_id']??null,FILTER_VALIDATE_INT);$sessionId=filter_var($input['trading_session_id']??null,FILTER_VALIDATE_INT);
    if($systemId===false)$systemId=null;if($strategyId===false)$strategyId=null;if($assetId===false)$assetId=null;if($sessionId===false)$sessionId=null;
    if(!$systemId&&!empty($account['default_system_id']))$systemId=(int)$account['default_system_id'];
    if($systemId&&!phase3_trade_lookup($db,$userId,'trading_systems',$systemId))throw new InvalidArgumentException('The selected trading system is invalid.');
    if($strategyId){$strategy=phase3_trade_lookup($db,$userId,'strategies',$strategyId);if(!$strategy)throw new InvalidArgumentException('The selected strategy is invalid.');if($systemId&&(int)$strategy['trading_system_id']!==$systemId)throw new InvalidArgumentException('The selected strategy does not belong to the selected trading system.');if(!$systemId)$systemId=(int)$strategy['trading_system_id'];}
    if($assetId&&!phase3_trade_lookup($db,$userId,'assets',$assetId))throw new InvalidArgumentException('The selected asset is invalid.');
    if(!$assetId){$symbol=strtoupper(trim((string)$input['symbol']));if($symbol!==''){$q=$db->prepare('SELECT id FROM assets WHERE user_id=? AND UPPER(symbol)=? LIMIT 1');$q->execute([$userId,$symbol]);$matched=$q->fetchColumn();if($matched)$assetId=(int)$matched;}}
    if($sessionId&&!phase3_trade_lookup($db,$userId,'trading_sessions',$sessionId))throw new InvalidArgumentException('The selected session is invalid.');
    $grade=trim((string)($input['grade']??''));if($grade!==''&&!in_array($grade,\App\Services\FeatureParityService::GRADES,true))throw new InvalidArgumentException('Invalid trade grade.');
    $timeframe=trim((string)($input['timeframe']??''));if($timeframe!==''&&!in_array($timeframe,['1m','5m','15m','30m','1h','4h','1d','1w'],true))throw new InvalidArgumentException('Invalid timeframe.');
    $screenshot=trim((string)($input['screenshot_path']??''));
    return [...$data,$systemId?:null,$strategyId?:null,$assetId?:null,$sessionId?:null,$grade?:null,$timeframe?:null,$screenshot?:null];
}

function phase3_trade_route(string $path,string $method,array $user):bool
{
    if($path!=='/trades')return false;$db=db();$userId=(int)$user['id'];
    if($method==='POST'){
        verify_csrf();$action=$_POST['action']??'';
        if($action==='delete'){$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);if(!$id)throw new InvalidArgumentException('Invalid trade.');$db->prepare('DELETE FROM trades WHERE id=? AND user_id=?')->execute([$id,$userId]);flash('success','Trade deleted.');redirect('/trades');}
        if($action!=='save')throw new InvalidArgumentException('Unknown trade action.');$id=filter_var($_POST['id']??null,FILTER_VALIDATE_INT);$data=phase3_trade_form_data($_POST,$user);[$accountId,$ticket,$symbol,$side,$status,$opened,$closed,$qty,$entry,$sl,$tp,$exit,$fees,$notes,$systemId,$strategyId,$assetId,$sessionId,$grade,$timeframe,$screenshot]=$data;
        if($id){$s=$db->prepare('UPDATE trades SET account_id=?,ticket=?,symbol=?,side=?,status=?,opened_at=?,closed_at=?,quantity=?,entry_price=?,stop_loss=?,take_profit=?,exit_price=?,fees=?,notes=?,trading_system_id=?,strategy_id=?,asset_id=?,trading_session_id=?,grade=?,timeframe=?,screenshot_path=? WHERE id=? AND user_id=?');$s->execute([$accountId,$ticket,$symbol,$side,$status,$opened,$closed,$qty,$entry,$sl,$tp,$exit,$fees,$notes,$systemId,$strategyId,$assetId,$sessionId,$grade,$timeframe,$screenshot,$id,$userId]);$savedId=$id;}else{$s=$db->prepare('INSERT INTO trades(account_id,ticket,symbol,side,status,opened_at,closed_at,quantity,entry_price,stop_loss,take_profit,exit_price,fees,notes,trading_system_id,strategy_id,asset_id,trading_session_id,grade,timeframe,screenshot_path,user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$accountId,$ticket,$symbol,$side,$status,$opened,$closed,$qty,$entry,$sl,$tp,$exit,$fees,$notes,$systemId,$strategyId,$assetId,$sessionId,$grade,$timeframe,$screenshot,$userId]);$savedId=(int)$db->lastInsertId();}
        flash('success',$id?'Trade updated.':'Trade added.');redirect('/trades?edit='.$savedId);
    }
    $s=$db->prepare('SELECT * FROM accounts WHERE user_id=? ORDER BY name');$s->execute([$userId]);$accounts=$s->fetchAll();
    $s=$db->prepare('SELECT id,name,ideal_risk,risk_tolerance FROM trading_systems WHERE user_id=? ORDER BY name');$s->execute([$userId]);$systems=$s->fetchAll();
    $s=$db->prepare('SELECT id,name,trading_system_id FROM strategies WHERE user_id=? ORDER BY name');$s->execute([$userId]);$strategies=$s->fetchAll();
    $s=$db->prepare('SELECT id,symbol,name,configuration FROM assets WHERE user_id=? ORDER BY symbol');$s->execute([$userId]);$assets=$s->fetchAll();
    $s=$db->prepare('SELECT id,name,start_time,end_time,timezone FROM trading_sessions WHERE user_id=? ORDER BY name');$s->execute([$userId]);$sessions=$s->fetchAll();
    $editTrade=null;$editId=filter_var($_GET['edit']??null,FILTER_VALIDATE_INT);if($editId){$s=$db->prepare('SELECT t.*,a.initial_balance,a.ideal_risk account_ideal_risk,a.risk_tolerance account_risk_tolerance,ar.symbol asset_symbol,ar.configuration asset_configuration FROM trades t JOIN accounts a ON a.id=t.account_id AND a.user_id=t.user_id LEFT JOIN assets ar ON ar.id=t.asset_id AND ar.user_id=t.user_id WHERE t.id=? AND t.user_id=?');$s->execute([$editId,$userId]);$editTrade=$s->fetch()?:null;if($editTrade&&empty($editTrade['trading_system_id'])){$q=$db->prepare('SELECT default_system_id FROM accounts WHERE id=? AND user_id=?');$q->execute([(int)$editTrade['account_id'],$userId]);$ds=$q->fetchColumn();if($ds)$editTrade['trading_system_id']=(int)$ds;}}
    $newTradeDefaults=[];if(!$editTrade&&$accounts)$newTradeDefaults=['account_id'=>(int)$accounts[0]['id'],'trading_system_id'=>(int)($accounts[0]['default_system_id']??0)];
    $where=['t.user_id=?'];$params=[$userId];$symbol=trim((string)($_GET['symbol']??''));$side=$_GET['side']??'';$status=$_GET['status']??'';$systemFilter=filter_var($_GET['trading_system_id']??null,FILTER_VALIDATE_INT);$assetFilter=filter_var($_GET['asset_id']??null,FILTER_VALIDATE_INT);$gradeFilter=trim((string)($_GET['grade']??''));$timeframeFilter=trim((string)($_GET['timeframe']??''));$outcomeFilter=trim((string)($_GET['outcome']??''));$minPnl=$_GET['min_pnl']??'';$maxPnl=$_GET['max_pnl']??'';$minR=$_GET['min_r']??'';$maxR=$_GET['max_r']??'';$dateFrom=trim((string)($_GET['date_from']??''));$dateTo=trim((string)($_GET['date_to']??''));
    if($symbol!==''){$where[]='t.symbol LIKE ?';$params[]='%'.$symbol.'%';}if(in_array($side,['long','short'],true)){$where[]='t.side=?';$params[]=$side;}if(in_array($status,['open','closed'],true)){$where[]='t.status=?';$params[]=$status;}if($systemFilter){$where[]='t.trading_system_id=?';$params[]=$systemFilter;}if($assetFilter){$where[]='t.asset_id=?';$params[]=$assetFilter;}if(in_array($gradeFilter,\App\Services\FeatureParityService::GRADES,true)){$where[]='t.grade=?';$params[]=$gradeFilter;}if(in_array($timeframeFilter,['1m','5m','15m','30m','1h','4h','1d','1w'],true)){$where[]='t.timeframe=?';$params[]=$timeframeFilter;}if($dateFrom!==''){$where[]='DATE(t.opened_at)>=?';$params[]=$dateFrom;}if($dateTo!==''){$where[]='DATE(t.opened_at)<=?';$params[]=$dateTo;}
    $s=$db->prepare('SELECT COUNT(*) FROM trades t WHERE '.implode(' AND ',$where));$s->execute($params);$total=(int)$s->fetchColumn();$page=max(1,(int)($_GET['page']??1));$pages=max(1,(int)ceil($total/25));$page=min($page,$pages);$offset=($page-1)*25;
    $s=$db->prepare('SELECT t.*,a.name account_name,a.currency,a.initial_balance,a.ideal_risk account_ideal_risk,a.risk_tolerance account_risk_tolerance,ts.name system_name,st.name strategy_name,ar.symbol asset_symbol,ar.configuration asset_configuration,sess.name session_name FROM trades t JOIN accounts a ON a.id=t.account_id AND a.user_id=t.user_id LEFT JOIN trading_systems ts ON ts.id=t.trading_system_id AND ts.user_id=t.user_id LEFT JOIN strategies st ON st.id=t.strategy_id AND st.user_id=t.user_id LEFT JOIN assets ar ON ar.id=t.asset_id AND ar.user_id=t.user_id LEFT JOIN trading_sessions sess ON sess.id=t.trading_session_id AND sess.user_id=t.user_id WHERE '.implode(' AND ',$where).' ORDER BY t.opened_at DESC,t.id DESC LIMIT 25 OFFSET '.$offset);$s->execute($params);$trades=$s->fetchAll();
    $riskService=new \App\Services\TradeRiskService();foreach($trades as &$t){if(empty($t['trading_system_id'])){$q=$db->prepare('SELECT default_system_id FROM accounts WHERE id=? AND user_id=? LIMIT 1');$q->execute([(int)$t['account_id'],$userId]);$ds=$q->fetchColumn();if($ds)$t['trading_system_id']=(int)$ds;}$t['pnl']=trade_pnl($t);$balanceBefore=(float)$t['initial_balance'];$cutoff=$t['closed_at']??$t['opened_at'];$prior=$db->prepare('SELECT * FROM trades WHERE user_id=? AND account_id=? AND status="closed" AND closed_at IS NOT NULL AND (closed_at < ? OR (closed_at = ? AND id < ?)) ORDER BY closed_at,id');$prior->execute([$userId,$t['account_id'],$cutoff,$cutoff,$t['id']]);foreach($prior->fetchAll() as $p)$balanceBefore+=(float)(trade_pnl($p)??0);$t['risk']=$riskService->calculate($db,$userId,$t,$balanceBefore);$t['outcome']=\App\Services\FeatureParityService::outcome($t['risk']['r_multiple']);}unset($t);
    if($outcomeFilter&&in_array($outcomeFilter,['Win','Loss','Breakeven'],true))$trades=array_values(array_filter($trades,fn($t)=>$t['outcome']===$outcomeFilter));
    if($minPnl!==''&&is_numeric($minPnl))$trades=array_values(array_filter($trades,fn($t)=>$t['pnl']!==null&&(float)$t['pnl']>=(float)$minPnl));if($maxPnl!==''&&is_numeric($maxPnl))$trades=array_values(array_filter($trades,fn($t)=>$t['pnl']!==null&&(float)$t['pnl']<=(float)$maxPnl));if($minR!==''&&is_numeric($minR))$trades=array_values(array_filter($trades,fn($t)=>$t['risk']['expected_r']!==null&&(float)$t['risk']['expected_r']>=(float)$minR));if($maxR!==''&&is_numeric($maxR))$trades=array_values(array_filter($trades,fn($t)=>$t['risk']['expected_r']!==null&&(float)$t['risk']['expected_r']<=(float)$maxR));
    $editRisk=null;if($editTrade){$editRisk=$riskService->calculate($db,$userId,$editTrade,(float)$editTrade['initial_balance']);}
    render('trades',['title'=>'Trades','accounts'=>$accounts,'systems'=>$systems,'strategies'=>$strategies,'assets'=>$assets,'sessions'=>$sessions,'editTrade'=>$editTrade,'newTradeDefaults'=>$newTradeDefaults,'editRisk'=>$editRisk,'trades'=>$trades,'grades'=>\App\Services\FeatureParityService::GRADES,'timeframes'=>['1m','5m','15m','30m','1h','4h','1d','1w'],'filters'=>['symbol'=>$symbol,'side'=>$side,'status'=>$status,'trading_system_id'=>$systemFilter,'asset_id'=>$assetFilter,'grade'=>$gradeFilter,'timeframe'=>$timeframeFilter,'outcome'=>$outcomeFilter,'min_pnl'=>$minPnl,'max_pnl'=>$maxPnl,'min_r'=>$minR,'max_r'=>$maxR,'date_from'=>$dateFrom,'date_to'=>$dateTo],'page'=>$page,'pages'=>$pages,'total'=>$total]);return true;
}
