<?php

declare(strict_types=1);
use App\Services\PeriodReviewService;
use App\Services\NotificationService;
require_once dirname(__DIR__).'/app/services/PeriodReviewService.php';
require_once dirname(__DIR__).'/app/services/NotificationService.php';

function phase12_require_schema(PDO $db): void
{
    $required = ['review_goals', 'period_reviews', 'period_review_goals', 'review_settings', 'review_exceptions'];
    $missing = [];
    $q = $db->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE() AND table_name = ?');
    foreach ($required as $table) {
        $q->execute([$table]);
        if ((int)$q->fetchColumn() === 0) {
            $missing[] = $table;
        }
    }
    if ($missing) {
        throw new RuntimeException('Phase 12 database schema is incomplete. Missing table(s): '.implode(', ', $missing).'. Run migrations 013_phase12_reviews_goals.sql and 014_phase12_review_exceptions.sql in order.');
    }
}

function phase12_seed_review_goals(PDO $db,int $uid):void{$items=[['Follow my trading plan','process'],['Take only planned setups','process'],['Avoid revenge trading','psychology'],['Avoid FOMO','psychology'],['Avoid overtrading','process'],['Respect my stop loss','risk'],['Do not move my stop loss','risk'],['Respect my maximum number of trades','risk'],['Stop when my loss limit is reached','risk'],['Stay emotionally neutral','psychology'],['Maintain focus','psychology'],['Trade only when mentally prepared','psychology'],['Reach my P&L target','performance'],['Achieve positive R','performance']];$q=$db->prepare('INSERT IGNORE INTO review_goals(user_id,name,goal_type) VALUES(?,?,?)');foreach($items as $item)$q->execute([$uid,$item[0],$item[1]]);}
function phase12_route(string $path,string $method,array $user):bool{$db=db();$uid=(int)$user['id'];phase12_require_schema($db);phase12_seed_review_goals($db,$uid);
 if($path==='/pre-post-review'||preg_match('#^/period-review/(\d+)$#',$path,$routeMatch)){PeriodReviewService::ensureCurrent($db,$uid);$forcedId=$routeMatch?(int)$routeMatch[1]:(int)($_GET['review']??0);if($method==='POST'){verify_csrf();$action=(string)($_POST['action']??'save');$id=(int)($_POST['review_id']??$forcedId);if($action==='delete'){if($id)PeriodReviewService::excludeReview($db,$uid,$id,trim((string)($_POST['exclude_reason']??'Review deleted/ignored')));flash('success','Review deleted and excluded from the schedule.');redirect('/pre-post-review');}$goalIds=array_values(array_filter(array_map('intval',(array)($_POST['goal_ids']??[])),fn($v)=>$v>0));$statuses=[];$notes=[];$targets=[];foreach($goalIds as $gid){$statuses[$gid]=(string)($_POST['goal_status'][$gid]??'pending');$notes[$gid]=(string)($_POST['goal_note'][$gid]??'');$targets[$gid]=['value'=>trim((string)($_POST['goal_target'][$gid]['value']??'')),'unit'=>trim((string)($_POST['goal_unit'][$gid]??''))];}$responses=[];foreach(['mood','energy','focus','market_condition','higher_timeframe_bias','markets','important_levels','primary_setup','secondary_setup','max_trades','max_daily_loss','max_risk','plan_adherence','risk_adherence','outside_plan','revenge','fomo','moved_stops','grade','best_trade','best_trade_reason','worst_trade','worst_trade_reason','did_well','did_poorly','mistake','change_tomorrow','replay','weekly_objective','monthly_objective','yearly_objective','skills','commitment'] as $f)$responses[$f]=trim((string)($_POST[$f]??''));$responses['stop_conditions']=array_values((array)($_POST['stop_conditions']??[]));PeriodReviewService::saveReview($db,$uid,$id,$responses,$goalIds,$statuses,$notes,$targets);flash('success','Review completed.');redirect('/pre-post-review?review='.$id);} $review=$forcedId?PeriodReviewService::review($db,$uid,$forcedId):null;$reviews=PeriodReviewService::current($db,$uid);if(!$review){$period=in_array((string)($_GET['period']??''),PeriodReviewService::PERIODS,true)?(string)$_GET['period']:'day';$type=in_array((string)($_GET['type']??''),PeriodReviewService::REVIEW_TYPES,true)?(string)$_GET['type']:'pre';foreach($reviews as $r)if($r['period_type']===$period&&$r['review_type']===$type){$review=$r;break;}}$goals=PeriodReviewService::goals($db,$uid);$goalRows=$review?PeriodReviewService::goalRows($db,$uid,(int)$review['id']):[];$responses=$review&&$review['responses_json']?json_decode((string)$review['responses_json'],true)?:[]:[];$suggestions=PeriodReviewService::suggestions($db,$uid);render('pre_post_review',['title'=>'Pre/Post Review','reviews'=>$reviews,'review'=>$review,'goals'=>$goals,'goalRows'=>$goalRows,'responses'=>$responses,'suggestions'=>$suggestions]);return true;}
 if($path==='/review-exceptions'){if($method==='POST'){verify_csrf();$settings=PeriodReviewService::settings($db,$uid);$tz=new DateTimeZone((string)$settings['timezone']);$start=new DateTimeImmutable((string)($_POST['start_date']??''),$tz);$end=new DateTimeImmutable((string)($_POST['end_date']??$_POST['start_date']??''),$tz);if($end<$start)throw new InvalidArgumentException('End date must be on or after start date.');$reason=trim((string)($_POST['reason']??''));if($reason==='')$reason='Day Off / PTO / No trading';$type=(string)($_POST['period_type']??'day');if(!in_array($type,PeriodReviewService::PERIODS,true))$type='day';PeriodReviewService::excludeRange($db,$uid,$type,$start,$end,$reason);flash('success','Review schedule exception saved.');redirect('/review-exceptions');}render('review_exceptions',['title'=>'Review Exceptions','exceptions'=>PeriodReviewService::exceptions($db,$uid)]);return true;}
 if($path==='/review-goals'){if($method==='POST'){verify_csrf();$action=(string)($_POST['action']??'save');$gid=(int)($_POST['goal_id']??0);if($action==='delete'){if($gid)$db->prepare('UPDATE review_goals SET is_active=0 WHERE id=? AND user_id=?')->execute([$gid,$uid]);flash('success','Goal removed.');redirect('/review-goals');}$name=trim((string)($_POST['name']??''));$type=(string)($_POST['goal_type']??'custom');PeriodReviewService::createGoal($db,$uid,$name,$type);flash('success','Goal saved.');redirect('/review-goals');}render('review_goals',['title'=>'Review Goals','goals'=>PeriodReviewService::goals($db,$uid)]);return true;}
 if($path==='/review-settings'){$settings=PeriodReviewService::settings($db,$uid);if($method==='POST'){verify_csrf();$tz=(string)($_POST['timezone']??$settings['timezone']);if(!in_array($tz,DateTimeZone::listIdentifiers(),true))throw new InvalidArgumentException('Invalid review timezone.');$fields=['day_pre_time','day_post_time','week_pre_time','week_post_time','month_pre_time','month_post_time','year_pre_time','year_post_time'];$vals=[];foreach($fields as $f){$v=(string)($_POST[$f]??'');if(!preg_match('/^\d{2}:\d{2}$/',$v))throw new InvalidArgumentException('Review times must use HH:MM.');$vals[$f]=$v.':00';}$ints=['week_pre_day','week_post_day','month_pre_day','year_pre_month','year_pre_day','year_post_month','year_post_day'];foreach($ints as $f)$vals[$f]=max(1,(int)($_POST[$f]??1));$db->prepare('UPDATE review_settings SET timezone=?,day_pre_time=?,day_post_time=?,week_pre_day=?,week_pre_time=?,week_post_day=?,week_post_time=?,month_pre_day=?,month_pre_time=?,month_post_time=?,year_pre_month=?,year_pre_day=?,year_pre_time=?,year_post_month=?,year_post_day=?,year_post_time=? WHERE user_id=?')->execute([$tz,$vals['day_pre_time'],$vals['day_post_time'],$vals['week_pre_day'],$vals['week_pre_time'],$vals['week_post_day'],$vals['week_post_time'],$vals['month_pre_day'],$vals['month_pre_time'],$vals['month_post_time'],$vals['year_pre_month'],$vals['year_pre_day'],$vals['year_pre_time'],$vals['year_post_month'],$vals['year_post_day'],$vals['year_post_time'],$uid]);flash('success','Review schedule updated.');redirect('/review-settings');}render('review_settings',['title'=>'Review Schedule','settings'=>$settings]);return true;}
 if($path==='/review-status'){$due=PeriodReviewService::due($db,$uid);$preBlock=false;$post=[];foreach($due as $r){if($r['period_type']==='day'&&$r['review_type']==='pre')$preBlock=true;if($r['period_type']==='day'&&$r['review_type']==='post')$post[]=$r;}header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'pre_blocked'=>$preBlock,'due'=>$due,'post_due'=>$post,'notification_unread'=>NotificationService::unread($db,$uid),'review_queue_count'=>count($due)],JSON_UNESCAPED_SLASHES);return true;}return false;}
