<?php
$csvTemplates=function_exists('account_csv_templates_data')&&!empty($accounts)?account_csv_templates_data((int)($accounts[0]['user_id']??0)):[];
$csvFields=class_exists('AccountCsvTemplateService')?AccountCsvTemplateService::FIELDS:[];
$defaultCsv=['symbol'=>'symbol','type'=>'type','opening_time'=>'opening_time_utc','closing_time'=>'closing_time_utc','quantity'=>'lots','entry_price'=>'opening_price','stop_loss'=>'stop_loss','take_profit'=>'take_profit','exit_price'=>'closing_price','profit'=>'profit_usd','fees'=>'commission_usd','close_reason'=>'close_reason','ticket'=>'ticket'];
$templatesByAccount=[];foreach($csvTemplates as $t)$templatesByAccount[(int)$t['account_id']][]=$t;
?>
<div class="page-title">Accounts</div><p class="page-subtitle">Manage trading accounts, currencies and starting balances.</p><div class="card form-card"><div class="section-heading"><div><h2>Add account</h2><div class="sub">Create an account once, then reuse it when recording trades.</div></div></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create"><div class="grid"><p><label>Name</label><input name="name" placeholder="Interactive Brokers" required></p><p><label>Currency</label><input name="currency" value="USD" maxlength="3" required></p><p><label>Initial balance</label><input name="initial_balance" type="number" step=".01" min="0" value="0" required></p></div><div class="actions"><button>Add account</button></div></form></div><?php foreach($accounts as $a):?><div class="card form-card"><div class="section-heading"><div><h2><?=e($a['name'])?></h2><div class="sub">Account configuration</div></div><span class="badge"><?=e($a['currency'])?></span></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=e($a['id'])?>"><div class="grid"><p><label>Name</label><input name="name" value="<?=e($a['name'])?>" required></p><p><label>Currency</label><input name="currency" value="<?=e($a['currency'])?>" maxlength="3" required></p><p><label>Initial balance</label><input name="initial_balance" type="number" step=".01" min="0" value="<?=e($a['initial_balance'])?>" required></p></div><div class="actions"><button>Save changes</button></form><form method="post" onsubmit="return confirm('Delete account and its trades?')"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=e($a['id'])?>"><button class="danger">Delete</button></form></div></div><?php endforeach;?>
<div class="card form-card"><div class="section-heading"><div><h2>Trade CSV Import</h2><div class="sub">Create an account-specific CSV template. The importer converts each broker/export format into the journal's standard trade fields.</div></div></div>
<?php foreach($accounts as $a):$templates=$templatesByAccount[(int)$a['id']]??[];?><div class="card"><div class="section-heading"><div><h3><?=e($a['name'])?></h3><div class="sub"><?=count($templates)?> template(s) configured</div></div></div>
<form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="account_id" value="<?=e($a['id'])?>"><input type="hidden" name="id" value=""><div class="grid"><p><label>Template name</label><input name="name" value="Default CSV" required></p><p><label>CSV delimiter</label><select name="delimiter_char"><option value=",">Comma (,)</option><option value=";">Semicolon (;)</option><option value="|">Pipe (|)</option><option value="\t">Tab</option></select></p><p><label>Date/time zone</label><select name="date_timezone"><?php foreach(['UTC','America/New_York','America/Chicago','America/Los_Angeles','America/Sao_Paulo'] as $tz):?><option value="<?=$tz?>"><?=$tz?></option><?php endforeach;?></select></p><p><label><input type="checkbox" name="has_header" value="1" checked> CSV has header row</label></p><p><label><input type="checkbox" name="is_default" value="1" checked> Use as default template for this account</label></p></div><h3>CSV column mapping</h3><div class="grid config-grid"><?php foreach($csvFields as $field=>$label):?><p><label><?=$label?><?=in_array($field,['symbol','type','opening_time','closing_time','quantity','entry_price','exit_price','profit','fees','ticket'],true)?' *':''?></label><input name="mapping[<?=$field?>]" value="<?=e($defaultCsv[$field]??'')?>" placeholder="Exact CSV header name"></p><?php endforeach;?></div><div class="actions"><button>Save CSV template</button></div></form>
<?php foreach($templates as $t):?><div class="card table-wrap"><div class="section-heading"><div><strong><?=e($t['name'])?></strong> <?php if($t['is_default']):?><span class="badge">Default</span><?php endif;?><div class="sub">Delimiter: <?=e($t['delimiter_char']==="\t"?'Tab':$t['delimiter_char'])?> · Time zone: <?=e($t['date_timezone'])?></div></div></div><div class="sub">Mapped columns: <?php $parts=[];foreach(($t['mapping']??[]) as $field=>$column)if($column!=='')$parts[]=e(($csvFields[$field]??$field).' → '.$column);echo implode(' · ',$parts);?></div><form method="post" class="actions"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=e($t['id'])?>"><button class="danger">Delete template</button></form></div><?php endforeach;?></div><?php endforeach;?>
<?php if(!$accounts):?><p class="muted">Create an account first, then configure its Trade CSV Import template.</p><?php endif;?></div>
