<h1>Bulk Trade Update</h1>
<p>Select multiple trades and apply the same system, strategy, session, grade or timeframe.</p>
<form method="post" class="card" id="bulk-form">
<?=csrf_field()?>
<div class="grid"><p><label>Field</label><select name="field" required><option value="grade">Grade</option><option value="timeframe">Timeframe</option><option value="trading_system_id">Trading system</option><option value="strategy_id">Strategy</option><option value="trading_session_id">Session</option></select></p>
<p><label>Value</label><select name="value" id="bulk-value" required><option value="">Select</option><?php foreach($grades as $x):?><option value="<?=$x?>"><?=$x?></option><?php endforeach;?></select></p></div>
<button>Update selected trades</button>
<div class="table-wrap"><table><tr><th><input type="checkbox" id="select-all"></th><th>ID</th><th>Symbol</th><th>Side</th><th>Status</th><th>Grade</th><th>Timeframe</th><th>Opened</th></tr>
<?php foreach($trades as $t):?><tr><td><input type="checkbox" name="trade_ids[]" value="<?=e($t['id'])?>"></td><td><?=e($t['id'])?></td><td><?=e($t['symbol'])?></td><td><?=e($t['side'])?></td><td><?=e($t['status'])?></td><td><?=e($t['grade']??'—')?></td><td><?=e($t['timeframe']??'—')?></td><td><?=e($t['opened_at'])?></td></tr><?php endforeach;?></table></div>
</form>
<script nonce="<?=e(csp_nonce())?>">(function(){const f=document.getElementById('bulk-form'),field=f.querySelector('[name=field]'),value=f.querySelector('[name=value]'),selectAll=document.getElementById('select-all');const data={grade:<?=json_encode(array_map(fn($x)=>['v'=>$x,'t'=>$x],$grades))?>,timeframe:<?=json_encode(array_map(fn($x)=>['v'=>$x,'t'=>$x],$timeframes))?>,trading_system_id:<?=json_encode(array_map(fn($x)=>['v'=>$x['id'],'t'=>$x['name']],$systems))?>,strategy_id:<?=json_encode(array_map(fn($x)=>['v'=>$x['id'],'t'=>$x['name']],$strategies))?>,trading_session_id:<?=json_encode(array_map(fn($x)=>['v'=>$x['id'],'t'=>$x['name']],$sessions))?>};function refresh(){value.innerHTML='<option value="">Select</option>';for(const x of (data[field.value]||[])){const o=document.createElement('option');o.value=x.v;o.textContent=x.t;value.appendChild(o)}}field.addEventListener('change',refresh);selectAll.addEventListener('change',()=>f.querySelectorAll('input[name="trade_ids[]"]').forEach(x=>x.checked=selectAll.checked));refresh()})();</script>
