<h1>Bulk Trade Update</h1>
<p>Select multiple trades and apply the same system, strategy, session, grade or timeframe.</p>
<div class="card form-card">
<div class="section-heading"><div><h2>Trade Filters</h2><div class="sub">Use the same filters available in Trade History to narrow the trades shown below.</div></div></div>
<form method="get" class="filter-grid" id="bulk-filters">
<p><label>Symbol</label><input name="symbol" value="<?=e($filters['symbol']??'')?>" placeholder="EURUSD"></p>
<p><label>Side</label><select name="side"><option value="">All sides</option><option value="long" <?=($filters['side']??'')==='long'?'selected':''?>>Long</option><option value="short" <?=($filters['side']??'')==='short'?'selected':''?>>Short</option></select></p>
<p><label>Status</label><select name="status"><option value="">All statuses</option><option value="open" <?=($filters['status']??'')==='open'?'selected':''?>>Open</option><option value="closed" <?=($filters['status']??'')==='closed'?'selected':''?>>Closed</option></select></p>
<p><label>System</label><select name="trading_system_id"><option value="">All systems</option><?php foreach($systems as $x):?><option value="<?=e($x['id'])?>" <?=((int)($filters['trading_system_id']??0)===(int)$x['id'])?'selected':''?>><?=e($x['name'])?></option><?php endforeach;?></select></p>
<p><label>Asset</label><select name="asset_id"><option value="">All assets</option><?php foreach(($assets??[]) as $x):?><option value="<?=e($x['id'])?>" <?=((int)($filters['asset_id']??0)===(int)$x['id'])?'selected':''?>><?=e($x['symbol'].' — '.$x['name'])?></option><?php endforeach;?></select></p>
<p><label>Grade</label><select name="grade"><option value="">All grades</option><?php foreach($grades as $g):?><option value="<?=$g?>" <?=($filters['grade']??'')===$g?'selected':''?>><?=$g?></option><?php endforeach;?></select></p>
<p><label>Timeframe</label><select name="timeframe"><option value="">All timeframes</option><?php foreach($timeframes as $tf):?><option value="<?=$tf?>" <?=($filters['timeframe']??'')===$tf?'selected':''?>><?=$tf?></option><?php endforeach;?></select></p>
<p><label>Outcome</label><select name="outcome"><option value="">All outcomes</option><?php foreach(['Win','Loss','Breakeven'] as $o):?><option value="<?=$o?>" <?=($filters['outcome']??'')===$o?'selected':''?>><?=$o?></option><?php endforeach;?></select></p>
<p><label>From</label><input type="date" name="date_from" value="<?=e($filters['date_from']??'')?>"></p><p><label>To</label><input type="date" name="date_to" value="<?=e($filters['date_to']??'')?>"></p>
<p><label>Min P&amp;L</label><input type="number" step=".01" name="min_pnl" value="<?=e($filters['min_pnl']??'')?>"></p><p><label>Max P&amp;L</label><input type="number" step=".01" name="max_pnl" value="<?=e($filters['max_pnl']??'')?>"></p>
<p><label>Min Expected R</label><input type="number" step=".1" name="min_r" value="<?=e($filters['min_r']??'')?>"></p><p><label>Max Expected R</label><input type="number" step=".1" name="max_r" value="<?=e($filters['max_r']??'')?>"></p>
<div class="actions filter-actions"><button type="submit">Apply filters</button><a class="secondary-link" href="/bulk-trades">Reset</a></div>
</form></div>
<form method="post" class="card" id="bulk-form">
<?=csrf_field()?>
<?php foreach(($filters??[]) as $k=>$v):if($v!==''&&$v!==null):?><input type="hidden" name="filter_<?=e($k)?>" value="<?=e((string)$v)\?>"><?php endif;endforeach;?>
<div class="section-heading"><div><h2>Bulk Update</h2><div class="sub">Select the filtered trades and apply the same system, strategy, session, grade or timeframe.</div></div></div>
<div class="grid"><p><label>Field</label><select name="field" required><option value="grade">Grade</option><option value="timeframe">Timeframe</option><option value="trading_system_id">Trading system</option><option value="strategy_id">Strategy</option><option value="trading_session_id">Session</option></select></p>
<p><label>Value</label><select name="value" id="bulk-value" required><option value="">Select</option><?php foreach($grades as $x):?><option value="<?=$x?>"><?=$x?></option><?php endforeach;?></select></p></div>
<div class="actions"><button>Update selected trades</button></div>
<div class="table-wrap"><table><thead><tr><th><input type="checkbox" id="select-all"></th><th>ID</th><th>Symbol</th><th>Side</th><th>Status</th><th>System</th><th>Strategy</th><th>Session</th><th>Grade</th><th>Timeframe</th><th>Opened</th></tr></thead><tbody>
<?php foreach($trades as $t):?><tr><td><input type="checkbox" name="trade_ids[]" value="<?=e($t['id'])?>"></td><td><?=e($t['id'])?></td><td><?=e($t['symbol'])?></td><td><?=e($t['side'])?></td><td><?=e($t['status'])?></td><td><?=e($t['system_name']??'—')?></td><td><?=e($t['strategy_name']??'—')?></td><td><?=e($t['session_name']??'—')?></td><td><?=e($t['grade']??'—')?></td><td><?=e($t['timeframe']??'—')?></td><td><?=e($t['opened_at'])?></td></tr><?php endforeach;?><?php if(!$trades):?><tr><td colspan="11" class="muted">No trades match the selected filters.</td></tr><?php endif;?></tbody></table></div>
</form>
<script nonce="<?=e(csp_nonce())?>">(function(){const f=document.getElementById('bulk-form'),field=f.querySelector('[name=field]'),value=f.querySelector('[name=value]'),selectAll=document.getElementById('select-all');const data={grade:<?=json_encode(array_map(fn($x)=>['v'=>$x,'t'=>$x],$grades))?>,timeframe:<?=json_encode(array_map(fn($x)=>['v'=>$x,'t'=>$x],$timeframes))?>,trading_system_id:<?=json_encode(array_map(fn($x)=>['v'=>$x['id'],'t'=>$x['name']],$systems))?>,strategy_id:<?=json_encode(array_map(fn($x)=>['v'=>$x['id'],'t'=>$x['name']],$strategies))?>,trading_session_id:<?=json_encode(array_map(fn($x)=>['v'=>$x['id'],'t'=>$x['name']],$sessions))?>};function refresh(){value.innerHTML='<option value="">Select</option>';for(const x of(data[field.value]||[])){const o=document.createElement('option');o.value=x.v;o.textContent=x.t;value.appendChild(o)}}field.addEventListener('change',refresh);selectAll?.addEventListener('change',()=>f.querySelectorAll('input[name="trade_ids[]"]').forEach(x=>x.checked=selectAll.checked));refresh()})();</script>
