<?php
$goalPerformance=$goalPerformance??['accounts'=>[],'accountPnl'=>[],'calendar'=>[],'year'=>[],'goals'=>[],'goalMap'=>[]];
$monthStart=$goalPerformance['monthStart'];$calendar=$goalPerformance['calendar'];$year=$goalPerformance['year'];
$yearTitle=$goalPerformance['yearStart']->format('Y');
$firstDow=(int)$monthStart->format('N');$daysInMonth=count($calendar);
?>
<div class="page-title">Dashboard</div><p class="page-subtitle">Performance overview, P&amp;L goals and trading activity</p>
<div class="stats-grid"><div class="metric"><div class="label">Profit Factor</div><div class="value"><?= $pf===null?'—':number_format($pf,2) ?></div><div class="hint">Gross Profit / Gross Loss</div></div><div class="metric"><div class="label">Expectancy</div><div class="value positive"><?= $exp===null?'—':number_format($exp,2).'R' ?></div><div class="hint">Average R per trade</div></div><div class="metric"><div class="label">Largest Win</div><div class="value positive"><?= $largestWin===null?'—':number_format($largestWin,2) ?></div><div class="hint">Best single trade</div></div><div class="metric"><div class="label">Largest Loss</div><div class="value negative"><?= $largestLoss===null?'—':number_format($largestLoss,2) ?></div><div class="hint">Worst single trade</div></div></div>

<div class="card"><div class="section-heading"><div><h2>P&amp;L Goals</h2><div class="sub">Current progress by account</div></div><a class="secondary-link" href="/goals">Manage goals</a></div><?php if(!$goalPerformance['goals']):?><p class="muted">No goals configured. Set daily, weekly, monthly and yearly targets.</p><?php else:?><div class="stats-grid"><?php foreach($goalPerformance['goals'] as $g):$id=(int)$g['account_id'];$p=$goalPerformance['accountPnl'][$id]??['today'=>0,'week'=>0,'month'=>0,'year'=>0];?><div class="metric"><div class="label"><?=e($g['account_name'])?> — Today</div><div class="value <?= $p['today']>=0?'positive':'negative' ?>"><?=number_format($p['today'],2)?></div><div class="hint">Goal <?=number_format((float)$g['daily_goal'],2)?></div></div><div class="metric"><div class="label"><?=e($g['account_name'])?> — Week</div><div class="value <?= $p['week']>=0?'positive':'negative' ?>"><?=number_format($p['week'],2)?></div><div class="hint">Goal <?=number_format((float)$g['weekly_goal'],2)?></div></div><div class="metric"><div class="label"><?=e($g['account_name'])?> — Month</div><div class="value <?= $p['month']>=0?'positive':'negative' ?>"><?=number_format($p['month'],2)?></div><div class="hint">Goal <?=number_format((float)$g['monthly_goal'],2)?></div></div><div class="metric"><div class="label"><?=e($g['account_name'])?> — Year</div><div class="value <?= $p['year']>=0?'positive':'negative' ?>"><?=number_format($p['year'],2)?></div><div class="hint">Goal <?=number_format((float)$g['yearly_goal'],2)?></div></div><?php endforeach;?></div><?php endif;?></div>

<div class="report-grid"><div class="card chart-card"><h2>Equity Curve (Expected R)</h2><div class="sub">Your cumulative trading performance over time</div><canvas id="equityChart"></canvas></div><div class="card chart-card"><h2>Account Balance Growth</h2><div class="sub">Your account balance progression over time</div><canvas id="balanceChart"></canvas></div><div class="card chart-card"><h2>R-Multiple Distribution</h2><div class="sub">How your trades are distributed across R-multiples</div><canvas id="rChart"></canvas></div><div class="card chart-card"><h2>System Performance</h2><div class="sub">Net P&amp;L by trading system</div><canvas id="systemChart"></canvas></div><div class="card chart-card"><h2>Monthly Performance</h2><div class="sub">Total net P&amp;L by month</div><canvas id="monthChart"></canvas></div><div class="card chart-card"><h2>Year Performance — <?=$yearTitle?></h2><div class="sub">Monthly net P&amp;L for the current year</div><canvas id="yearChart"></canvas></div></div>

<div class="card"><div class="section-heading"><div><h2>Monthly P&amp;L Calendar — <?=e($monthStart->format('F Y'))?></h2><div class="sub">Closed-trade net P&amp;L by day</div></div></div><div class="pnl-calendar"><div class="calendar-head"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="calendar-grid"><?php for($i=1;$i<$firstDow;$i++):?><div class="calendar-day empty"></div><?php endfor;foreach($calendar as $date=>$pnl):$day=(int)substr($date,8,2);?><div class="calendar-day <?= $pnl>0?'profit':($pnl<0?'loss':'flat') ?>"><span class="calendar-date"><?=$day?></span><strong><?=number_format($pnl,2)?></strong></div><?php endforeach;?></div></div></div>

<div class="card"><h2>Performance Snapshot</h2><div class="sub">Current journal statistics</div><div class="mini-grid"><div class="mini-stat"><strong><?=number_format($count)?></strong><span class="muted">Closed trades</span></div><div class="mini-stat"><strong class="positive"><?=$wr===null?'—':number_format($wr,1).'%';?></strong><span class="muted">Win rate</span></div><div class="mini-stat"><strong class="<?= $net>=0?'positive':'negative' ?>"><?=number_format($net,2)?></strong><span class="muted">Net P&amp;L</span></div></div></div>
<style>.pnl-calendar{width:100%;overflow:auto}.calendar-head,.calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(75px,1fr));min-width:525px}.calendar-head span{padding:6px;text-align:center;font-size:9px;text-transform:uppercase;color:#94a3b8;font-weight:700}.calendar-day{min-height:62px;border:1px solid #edf1f5;margin:-1px 0 0 -1px;padding:6px;display:flex;flex-direction:column;justify-content:space-between}.calendar-day .calendar-date{font-size:9px;color:#94a3b8}.calendar-day strong{font-size:11px}.calendar-day.profit{background:#f0fdf4}.calendar-day.loss{background:#fff1f2}.calendar-day.flat{background:#fafbfc}.calendar-day.empty{background:#fff}</style>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script nonce="<?=e(csp_nonce())?>">const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:8}}},y:{ticks:{font:{size:8}}}}};function chart(id,type,labels,data){new Chart(document.getElementById(id),{type,data:{labels,datasets:[{data,borderWidth:1.5,pointRadius:type==='line'?1.5:0,fill:type==='line'?false:true,backgroundColor:type==='line'?'rgba(239,107,79,.16)':'rgba(239,107,79,.82)',borderColor:'#ec6a4f',tension:.25}]},options:base})}chart('equityChart','line',<?=json_encode($equityLabels)?>,<?=json_encode($equityData)?>);chart('balanceChart','line',<?=json_encode($balanceLabels)?>,<?=json_encode($balanceData)?>);chart('rChart','bar',<?=json_encode($rLabels)?>,<?=json_encode($rData)?>);chart('systemChart','bar',<?=json_encode($systemLabels)?>,<?=json_encode($systemData)?>);chart('monthChart','bar',<?=json_encode($monthLabels)?>,<?=json_encode($monthData)?>);chart('yearChart','bar',<?=json_encode(array_map(fn($m)=>date('M',strtotime($m.'-01')),array_keys($year)))?>,<?=json_encode(array_values($year))?>);</script>
