<?php
$goalPerformance=$goalPerformance??['accounts'=>[],'systems'=>[],'accountPnl'=>[],'systemPnl'=>[],'calendar'=>[],'year'=>[],'goals'=>[],'goalMap'=>[],'dailyGoal'=>0,'weeklyGoal'=>0,'monthlyGoal'=>0,'yearlyGoal'=>0];
$monthStart=$goalPerformance['monthStart'];$calendar=$goalPerformance['calendar'];$year=$goalPerformance['year'];
$yearTitle=$goalPerformance['yearStart']->format('Y');$firstDow=(int)$monthStart->format('N');$daysInMonth=count($calendar);
$dailyGoal=(float)$goalPerformance['dailyGoal'];$monthlyGoal=(float)$goalPerformance['monthlyGoal'];$yearlyGoal=(float)$goalPerformance['yearlyGoal'];
?>
<div class="page-title">Dashboard</div><p class="page-subtitle">Performance overview, P&amp;L goals and trading activity</p>
<div class="stats-grid"><div class="metric"><div class="label">Profit Factor</div><div class="value"><?= $pf===null?'—':number_format($pf,2) ?></div><div class="hint">Gross Profit / Gross Loss</div></div><div class="metric"><div class="label">Expectancy</div><div class="value positive"><?= $exp===null?'—':number_format($exp,2).'R' ?></div><div class="hint">Average R per trade</div></div><div class="metric"><div class="label">Largest Win</div><div class="value positive"><?= $largestWin===null?'—':number_format($largestWin,2) ?></div><div class="hint">Best single trade</div></div><div class="metric"><div class="label">Largest Loss</div><div class="value negative"><?= $largestLoss===null?'—':number_format($largestLoss,2) ?></div><div class="hint">Worst single trade</div></div></div>

<div class="card"><div class="section-heading"><div><h2>P&amp;L Goals</h2><div class="sub">Account totals and system-specific targets. ✓ means the target has been reached.</div></div><a class="secondary-link" href="/goals">Manage goals</a></div><?php if(!$goalPerformance['goals']):?><p class="muted">No goals configured. Set targets by account and optionally by trading system.</p><?php else:?><div class="stats-grid"><?php foreach($goalPerformance['goals'] as $g):$id=(int)$g['account_id'];$p=$g['trading_system_id']!==null?($goalPerformance['systemPnl'][(int)$g['trading_system_id']]??['today'=>0,'week'=>0,'month'=>0,'year'=>0]):($goalPerformance['accountPnl'][$id]??['today'=>0,'week'=>0,'month'=>0,'year'=>0]);$scope=$g['system_name']??'All systems';?><div class="metric"><div class="label"><?=e($g['account_name'])?> · <?=e($scope)?> · Today</div><div class="value <?= $p['today']>=(float)$g['daily_goal']?'goal-hit':($p['today']>=0?'positive':'negative') ?>"><?= $p['today']>=(float)$g['daily_goal']&&((float)$g['daily_goal']>0)?'✓ ':'' ?><?=number_format($p['today'],2)?></div><div class="hint">Goal <?=number_format((float)$g['daily_goal'],2)?></div></div><div class="metric"><div class="label"><?=e($g['account_name'])?> · <?=e($scope)?> · Week</div><div class="value <?= $p['week']>=(float)$g['weekly_goal']?'goal-hit':($p['week']>=0?'positive':'negative') ?>"><?= $p['week']>=(float)$g['weekly_goal']&&((float)$g['weekly_goal']>0)?'✓ ':'' ?><?=number_format($p['week'],2)?></div><div class="hint">Goal <?=number_format((float)$g['weekly_goal'],2)?></div></div><div class="metric"><div class="label"><?=e($g['account_name'])?> · <?=e($scope)?> · Month</div><div class="value <?= $p['month']>=(float)$g['monthly_goal']?'goal-hit':($p['month']>=0?'positive':'negative') ?>"><?= $p['month']>=(float)$g['monthly_goal']&&((float)$g['monthly_goal']>0)?'✓ ':'' ?><?=number_format($p['month'],2)?></div><div class="hint">Goal <?=number_format((float)$g['monthly_goal'],2)?></div></div><div class="metric"><div class="label"><?=e($g['account_name'])?> · <?=e($scope)?> · Year</div><div class="value <?= $p['year']>=(float)$g['yearly_goal']?'goal-hit':($p['year']>=0?'positive':'negative') ?>"><?= $p['year']>=(float)$g['yearly_goal']&&((float)$g['yearly_goal']>0)?'✓ ':'' ?><?=number_format($p['year'],2)?></div><div class="hint">Goal <?=number_format((float)$g['yearly_goal'],2)?></div></div><?php endforeach;?></div><?php endif;?></div>

<div class="report-grid"><div class="card chart-card"><h2>Equity Curve (Expected R)</h2><div class="sub">Your cumulative trading performance over time</div><canvas id="equityChart"></canvas></div><div class="card chart-card"><h2>Account Balance Growth</h2><div class="sub">Your account balance progression over time</div><canvas id="balanceChart"></canvas></div><div class="card chart-card"><h2>R-Multiple Distribution</h2><div class="sub">How your trades are distributed across R-multiples</div><canvas id="rChart"></canvas></div><div class="card chart-card"><h2>System Performance</h2><div class="sub">Net P&amp;L by trading system</div><canvas id="systemChart"></canvas></div><div class="card chart-card"><h2>Monthly Performance</h2><div class="sub">Net P&amp;L by month with the monthly goal reference</div><canvas id="monthChart"></canvas></div><div class="card chart-card"><h2>Year Performance — <?=$yearTitle?></h2><div class="sub">Monthly net P&amp;L with the yearly goal reference</div><canvas id="yearChart"></canvas></div></div>

<div class="card"><div class="section-heading"><div><h2>Monthly P&amp;L Calendar — <?=e($monthStart->format('F Y'))?></h2><div class="sub">Closed-trade net P&amp;L by day. ✓ = daily goal reached; • = no goal hit.</div></div></div><div class="pnl-calendar"><div class="calendar-head"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div class="calendar-grid"><?php for($i=1;$i<$firstDow;$i++):?><div class="calendar-day empty"></div><?php endfor;foreach($calendar as $date=>$pnl):$day=(int)substr($date,8,2);$hit=$dailyGoal>0&&(float)$pnl>=$dailyGoal;?><div class="calendar-day <?= $hit?'goal-hit':($pnl>0?'profit':($pnl<0?'loss':'flat')) ?>"><span class="calendar-date"><?=$day?> <?= $hit?'✓':'•' ?></span><strong><?=number_format($pnl,2)?></strong><?php if($dailyGoal>0):?><small>Goal <?=number_format($dailyGoal,2)?></small><?php endif;?></div><?php endforeach;?></div></div></div>

<div class="card"><h2>Performance Snapshot</h2><div class="sub">Current journal statistics</div><div class="mini-grid"><div class="mini-stat"><strong><?=number_format($count)?></strong><span class="muted">Closed trades</span></div><div class="mini-stat"><strong class="positive"><?=$wr===null?'—':number_format($wr,1).'%';?></strong><span class="muted">Win rate</span></div><div class="mini-stat"><strong class="<?= $net>=0?'positive':'negative' ?>"><?=number_format($net,2)?></strong><span class="muted">Net P&amp;L</span></div></div></div>
<style>.pnl-calendar{width:100%;overflow:auto}.calendar-head,.calendar-grid{display:grid;grid-template-columns:repeat(7,minmax(75px,1fr));min-width:525px}.calendar-head span{padding:6px;text-align:center;font-size:9px;text-transform:uppercase;color:#94a3b8;font-weight:700}.calendar-day{min-height:72px;border:1px solid #edf1f5;margin:-1px 0 0 -1px;padding:6px;display:flex;flex-direction:column;justify-content:space-between}.calendar-day .calendar-date{font-size:9px;color:#94a3b8}.calendar-day strong{font-size:11px}.calendar-day small{font-size:8px;color:#94a3b8}.calendar-day.profit{background:#f0fdf4}.calendar-day.loss{background:#fff1f2}.calendar-day.flat{background:#fafbfc}.calendar-day.goal-hit{background:#ecfdf5;border:2px solid #16a34a;margin:-2px 0 0 -2px}.calendar-day.goal-hit .calendar-date{color:#15803d;font-weight:800}.goal-hit{color:#15803d!important;font-weight:800}.calendar-day.empty{background:#fff}</style>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script nonce="<?=e(csp_nonce())?>">const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{font:{size:8}}},y:{ticks:{font:{size:8}}}}};function chart(id,type,labels,data,goal=null,goalLabel='Goal'){const datasets=[{label:'Actual',data,borderWidth:1.5,pointRadius:type==='line'?1.5:0,fill:type==='line'?false:true,backgroundColor:type==='line'?'rgba(239,107,79,.16)':'rgba(239,107,79,.82)',borderColor:'#ec6a4f',tension:.25}];if(goal!==null&&goal>0)datasets.push({label:goalLabel,data:labels.map(()=>goal),borderWidth:1.5,borderDash:[5,4],pointRadius:0,fill:false,borderColor:'#64748b'});new Chart(document.getElementById(id),{type,data:{labels,datasets},options:{...base,plugins:{...base.plugins,legend:{display:goal!==null&&goal>0,position:'top'}}}})}chart('equityChart','line',<?=json_encode($equityLabels)?>,<?=json_encode($equityData)?>);chart('balanceChart','line',<?=json_encode($balanceLabels)?>,<?=json_encode($balanceData)?>);chart('rChart','bar',<?=json_encode($rLabels)?>,<?=json_encode($rData)?>);chart('systemChart','bar',<?=json_encode($systemLabels)?>,<?=json_encode($systemData)?>);chart('monthChart','bar',<?=json_encode($monthLabels)?>,<?=json_encode($monthData)?>,<?=$monthlyGoal?>,'Monthly goal');chart('yearChart','bar',<?=json_encode(array_map(fn($m)=>date('M',strtotime($m.'-01')),array_keys($year)))?>,<?=json_encode(array_values($year))?>,<?=$yearlyGoal?>,'Yearly goal');</script>
