<?php $title='Import Trades';$templates=$templates??[];$selectedAccount=(int)($selectedAccount??0);$selectedTemplate=(int)($selectedTemplate??0); ?>
<h1>Import Trades</h1>
<p>Choose the account first. Its default Trade CSV template is selected automatically, so each broker/account can use a different CSV format.</p>
<form method="post" enctype="multipart/form-data" class="card" id="csv-import-form">
<?=csrf_field()?>
<div class="grid"><label>Account<select name="account_id" id="csv-account" required><option value="">Select account</option><?php foreach($accounts as $account):?><option value="<?= (int)$account['id'] ?>" <?=((int)$account['id']===$selectedAccount)?'selected':''?>><?=e($account['name'])?> (<?=e($account['currency'])?>)</option><?php endforeach;?></select></label><label>Trade CSV template<select name="template_id" id="csv-template" required><option value="">Select account first</option></select></label></div>
<label>CSV file<input type="file" name="csv_file" accept=".csv,text/csv" required></label><div id="csv-template-info" class="sub"></div><div id="csv-smart-info" class="sub" style="margin-top:6px"></div><p>Maximum size: 5 MB. Standard templates use your manual field mapping. Smart CSV Import uses your manual mappings first, then automatically fills supported Interactive Brokers fields that were not mapped.</p>
<div class="actions"><button name="action" value="preview" type="submit" class="secondary">Preview CSV</button><button name="action" value="import" type="submit">Import CSV</button></div></form>
<?php if(!empty($preview)):?><div class="card"><h2>Preview</h2><p>Rows inspected: <strong><?=number_format((int)$preview['sample_count'])?></strong> · Generated trades: <strong><?=number_format((int)$preview['valid'])?></strong> · Invalid: <strong><?=number_format((int)$preview['invalid'])?></strong></p><?php if(($preview['mode']??'standard')==='interactive_brokers_smart'&&!empty($preview['generated_trades'])): ?><div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Symbol</th><th>Side</th><th>Status</th><th>Opened</th><th>Closed</th><th>Qty</th><th>Entry</th><th>Stop Loss</th><th>Take Profit</th><th>Exit</th><th>Calculated P&amp;L</th></tr></thead><tbody><?php foreach($preview['generated_trades'] as $trade):$pnl=$trade['status']==='closed'?($trade['side']==='long'?($trade['exit']-$trade['entry'])*$trade['quantity']:($trade['entry']-$trade['exit'])*$trade['quantity']):0; ?><tr><td><?=e($trade['ticket'])?></td><td><?=e($trade['symbol'])?></td><td><?=e(ucfirst($trade['side']))?></td><td><?=e(ucfirst($trade['status']))?></td><td><?=e($trade['opened_at'])?></td><td><?=e($trade['closed_at']??'—')?></td><td><?=number_format((float)$trade['quantity'],4)?></td><td><?=number_format((float)$trade['entry'],4)?></td><td><?=isset($trade['stop_loss'])&&$trade['stop_loss']!==null?number_format((float)$trade['stop_loss'],4):'—'?></td><td><?=isset($trade['take_profit'])&&$trade['take_profit']!==null?number_format((float)$trade['take_profit'],4):'—'?></td><td><?=isset($trade['exit'])&&$trade['exit']!==null?number_format((float)$trade['exit'],4):'—'?></td><td class="<?=$pnl>=0?'positive':'negative'?>"><?=number_format($pnl,2)?></td></tr><?php endforeach;?></tbody></table></div><p class="muted">Smart CSV Import used manual mappings first and broker-aware fallback for unmapped fields. Realized P&amp;L is calculated from entry/exit fills when the export does not provide profit. Fees default to 0 when no mapped fee value is available.</p><?php endif;?><?php if($preview['errors']):?><ul><?php foreach($preview['errors'] as $x):?><li><?=e($x)?></li><?php endforeach;?></ul><?php endif;?><p class="muted">Preview does not write trades.</p></div><?php endif;?>
<script nonce="<?=e(csp_nonce())?>">(function(){const data=<?=json_encode($templates,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>,account= document.getElementById('csv-account'),template=document.getElementById('csv-template'),info=document.getElementById('csv-template-info'),smartInfo=document.getElementById('csv-smart-info'),wanted=<?=json_encode($selectedTemplate)?>;function load(){const id=Number(account.value);template.innerHTML='<option value="">Select template</option>';data.filter(t=>Number(t.account_id)===id).forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.name+(Number(t.is_default)?' — Default':'');if(Number(t.id)===Number(wanted))o.selected=true;template.appendChild(o);});show();}function show(){const t=data.find(x=>Number(x.id)===Number(template.value));info.textContent=t?((t.import_mode==='smart_csv'?'Smart CSV Import':'Standard Trade CSV')+' · Delimiter: '+(t.delimiter_char==='\t'?'Tab':t.delimiter_char)+' · Time zone: '+t.date_timezone+' · '+(Number(t.has_header)?'Header row enabled':'No header row')):'';const accountText=account.options[account.selectedIndex]?.textContent?.toLowerCase()||'';smartInfo.textContent=(t&&t.import_mode==='smart_csv'&&accountText.includes('interactive brokers'))?'Interactive Brokers Smart Import detected: manual mappings are used first; unmapped fields are filled automatically where supported.':' ';}account.addEventListener('change',function(){template.value='';load();});template.addEventListener('change',show);load();})();</script>
